# environment-specific settings will be deep merged with the common hash, overriding values therein

common:
  providers:
    - twitter
    - open_id
    - google
    - facebook
    - linked_in
    - github
  google_analytics_id: 
  organization:
    name: Org Name
    city: City
    state: State
    url: http://geeks.codeforamerica.org
    twitter: codeforamerica
    email: corps@codeforamerica.org
    host: heroku
    host_url: geeks@codeforamerica.org
    logotype: GeekCorps
development:
  auth_credentials:
    github:
      key: developmentkey
      secret: devseekrit!
    twitter:
      key: skeletonkey
      secret: seekrit!
    facebook:
      key: skeletonkey
      secret: seekrit!
    linked_in:
      key:
      secret: seekrit!
      
