require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DetailsController do

  # This should return the minimal set of attributes required to create a valid
  # Detail. As you add validations to Detail, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all details as @details" do
      detail = Detail.create! valid_attributes
      get :index
      assigns(:details).should eq([detail])
    end
  end

  describe "GET show" do
    it "assigns the requested detail as @detail" do
      detail = Detail.create! valid_attributes
      get :show, :id => detail.id.to_s
      assigns(:detail).should eq(detail)
    end
  end

  describe "GET new" do
    it "assigns a new detail as @detail" do
      get :new
      assigns(:detail).should be_a_new(Detail)
    end
  end

  describe "GET edit" do
    it "assigns the requested detail as @detail" do
      detail = Detail.create! valid_attributes
      get :edit, :id => detail.id.to_s
      assigns(:detail).should eq(detail)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Detail" do
        expect {
          post :create, :detail => valid_attributes
        }.to change(Detail, :count).by(1)
      end

      it "assigns a newly created detail as @detail" do
        post :create, :detail => valid_attributes
        assigns(:detail).should be_a(Detail)
        assigns(:detail).should be_persisted
      end

      it "redirects to the created detail" do
        post :create, :detail => valid_attributes
        response.should redirect_to(Detail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved detail as @detail" do
        # Trigger the behavior that occurs when invalid params are submitted
        Detail.any_instance.stub(:save).and_return(false)
        post :create, :detail => {}
        assigns(:detail).should be_a_new(Detail)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Detail.any_instance.stub(:save).and_return(false)
        post :create, :detail => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested detail" do
        detail = Detail.create! valid_attributes
        # Assuming there are no other details in the database, this
        # specifies that the Detail created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Detail.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => detail.id, :detail => {'these' => 'params'}
      end

      it "assigns the requested detail as @detail" do
        detail = Detail.create! valid_attributes
        put :update, :id => detail.id, :detail => valid_attributes
        assigns(:detail).should eq(detail)
      end

      it "redirects to the detail" do
        detail = Detail.create! valid_attributes
        put :update, :id => detail.id, :detail => valid_attributes
        response.should redirect_to(detail)
      end
    end

    describe "with invalid params" do
      it "assigns the detail as @detail" do
        detail = Detail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Detail.any_instance.stub(:save).and_return(false)
        put :update, :id => detail.id.to_s, :detail => {}
        assigns(:detail).should eq(detail)
      end

      it "re-renders the 'edit' template" do
        detail = Detail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Detail.any_instance.stub(:save).and_return(false)
        put :update, :id => detail.id.to_s, :detail => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested detail" do
      detail = Detail.create! valid_attributes
      expect {
        delete :destroy, :id => detail.id.to_s
      }.to change(Detail, :count).by(-1)
    end

    it "redirects to the details list" do
      detail = Detail.create! valid_attributes
      delete :destroy, :id => detail.id.to_s
      response.should redirect_to(details_url)
    end
  end

end
